### ISSUE TITLE
Releases tag

### ISSUE THREAD

**Issue by anonymous09** [hwmay/pordb3#1]
Hi! Can you make release tag? I'm maintainer, and release tags can help me and other maintainers. So, the links with release tag will be like 
https://github.com/hwmay/pordb3/releases/tag/release-1.9.8.tar.gz

**Comment by hwmay** [comment]
Done, even it is only an empty file, because software is not distributed via a tar.gz file

**Comment by hwmay** [comment]
New file added

**Comment by anonymous09** [comment]
Sorry, but you do it wrong. You should not add some files in project. Instead you should use git feature. See https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by hwmay** [comment]
OK, done!
